# Generated by Django 2.1.7 on 2019-02-25 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Employee Full Name')),
                ('position', models.CharField(max_length=120, verbose_name='Employee Position')),
                ('join_date', models.DateField(verbose_name='Employee Join Date')),
                ('salary', models.PositiveIntegerField(default=500, verbose_name='Employee Salary')),
                ('chief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
            },
        ),
    ]
